apiVersion: v1
kind: Pod
metadata:
  name: ipc-client
  labels:
    app: ipc-client
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep infinity
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:23244e61eaee6a986e1ac26def05a6eeefa3150b9e740787d8ec0be765b6c8ec
    imagePullPolicy: IfNotPresent
    name: ipc-client
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - ipc-server
        topologyKey: "kubernetes.io/hostname"
---
apiVersion: v1
kind: Pod
metadata:
  name: ipc-server
  labels:
    app: ipc-server
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - sleep infinity
    image: quay.io/openshift-release-dev/ocp-v4.0-art-dev@sha256:23244e61eaee6a986e1ac26def05a6eeefa3150b9e740787d8ec0be765b6c8ec
    imagePullPolicy: IfNotPresent
    name: ipc-server